#mongoDB만 로컬로 띄우고자 할 때 사용.

services:
  mongodb:
    image: mongo:latest
    container_name: my-local-mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234

volumes:
  mongodb_data: